In [94]:
import requests
import cloudscraper
from bs4 import BeautifulSoup
import pandas as pd
import re
import unicodedata

donnees = []
scraper = cloudscraper.create_scraper()

for j in range(1,30):
    if j==1:  
        page = requests.get("https://www.etreproprio.com/annonces/thf.ld69#list")
    else:
        page = requests.get("https://www.etreproprio.com/annonces/thf.ld69.odd.g"+str(j)+"#list")
        
    soup = BeautifulSoup(page.content, "html.parser")
    temp = soup.find("div", class_='ep-search-list-wrapper').find_all("a")
    
    liens = []
    for i in range(len(temp)):
        if "https://www.etreproprio.com/immobilier-" in temp[i]['href']:
            liens.append(temp[i]['href'])
    
    for lien in liens:
        try:
            page_annonce = scraper.get(lien)
            soup_ = BeautifulSoup(page_annonce.content, 'lxml')

            try:
                # "Vente Appartement 75 m² Paris-14e"
                titre = soup_.find("title").text.strip()
                titre = unicodedata.normalize("NFKC", titre)
            except:
                titre = None

            try:
                # "Appartement 75 m² à Paris-14e"
                description_h1 = soup_.find("h1", class_='annonce-immobilier').text.strip()
                description_h1 = unicodedata.normalize("NFKC", description_h1)
            except:
                description_h1 = None

            try:
                # Extrait la ville depuis le titre : "Vente Appartement 75 m² Paris-14e" → "Paris-14e"
                ville = soup_.find("title").text.strip().split("²")[-1].strip()
            except:
                ville = None

            try:
                prix = soup_.find("div", class_='ep-price').text.strip()
                prix = int(prix.replace(" ", "").replace("\xa0", "").replace("€", ""))
            except:
                prix = None

            try:
                surface = soup_.find("div", class_='ep-area').text.strip()
                surface = int(surface.replace("\xa0", "").replace("m²", "").strip())
            except:
                surface = None

            try:
                type_bien = titre.split(" ")[1]  # le 2ème mot après "Vente"
            except:
                type_bien = None

            try:
                desc_texte = soup_.find("div", class_='ep-desc-truncated').text.strip()
                desc_texte = unicodedata.normalize("NFKC", desc_texte)
            except:
                desc_texte = None
            
            try:
                etage = None
                if desc_texte:
                # Cas 1 — chiffres
                    etage_match = re.search(r'(\d+)\s*(?:[eèéê?][mr]?[eèé]?|°)?\s*(?:et\s+)?(?:\(dernier\)|dernier)?\s*[eé]tage', desc_texte, re.IGNORECASE)
                    if etage_match:
                        etage = int(etage_match.group(1))
                # Cas 2 — lettres
                    else:
                        etages_lettres = {
                            "premier": 1, "première": 1, "premiere": 1,
                            "deuxième": 2, "deuxieme": 2,
                            "troisième": 3, "troisieme": 3,
                            "quatrième": 4, "quatrieme": 4,
                            "cinquième": 5, "cinquieme": 5,
                            "sixième": 6, "sixieme": 6,
                            "septième": 7, "septieme": 7,
                            "huitième": 8, "huitieme": 8,
                            "neuvième": 9, "neuvieme": 9,
                            "dixième": 10, "dixieme": 10,
                        }
                        for mot, num in etages_lettres.items():
                            if mot in desc_texte.lower():
                                etage = num
                                break
                # Cas 3 — rez-de-chaussée
                    if etage is None:
                        rdc_patterns = ["rez-de-chaussée", "rez de chaussée","rez-de-chaussee", "rez de chaussee", "rdc", "r.d.c"]
                        if any(p in desc_texte.lower() for p in rdc_patterns):
                            etage = 0
            except:
                etage = None

            try:
                dpe = soup_.find("div", class_='dpe-diagram').find("div", class_='selected').text.strip()
            except:
                dpe = None

            try:
                pieces = soup_.find("div", class_='ep-room').text.strip()
                pieces = int(pieces.replace("pièces", "").replace("pièce", "").strip())
            except:
                pieces = None

            print(f"Titre: {titre} | Ville: {ville} | Prix: {prix} | Surface: {surface} | Type: {type_bien} | Etage: {etage} | Pièces: {pieces} | DPE: {dpe}")

            donnees.append({
                "titre": titre,
                "description": description_h1,
                "ville": ville,
                "type_bien": type_bien,
                "etage": etage,
                "prix": prix,
                "surface": surface,
                "pieces": pieces,
                "DPE": dpe,
                "full_description": desc_texte,
                "lien": lien
            })

        except Exception as e:
            print(f"Erreur sur {lien} : {e}")
            continue

# Création du DataFrame
df = pd.DataFrame(donnees)
df["prix"] = pd.to_numeric(df["prix"], errors="coerce")
df["surface"] = pd.to_numeric(df["surface"], errors="coerce")
df["pieces"] = pd.to_numeric(df["pieces"], errors="coerce").astype("Int64")
df["etage"] = pd.to_numeric(df["etage"], errors="coerce").astype("Int64")

print(df)

Titre: Vente Appartement 72 m2 Francheville | Ville: Francheville | Prix: 269000 | Surface: 72 | Type: Appartement | Etage: None | Pièces: 3 | DPE: D
Titre: Vente Appartement 78 m2 Villeurbanne | Ville: Villeurbanne | Prix: 293000 | Surface: 78 | Type: Appartement | Etage: 3 | Pièces: 4 | DPE: C
Titre: Vente Appartement 208 m2 Feyzin | Ville: Feyzin | Prix: 380000 | Surface: 208 | Type: Appartement | Etage: 0 | Pièces: 5 | DPE: A
Titre: Vente Appartement 106 m2 Villefranche-Sur-Saone | Ville: Villefranche-Sur-Saone | Prix: 239000 | Surface: 106 | Type: Appartement | Etage: None | Pièces: 5 | DPE: D
Titre: Vente Maison 154 m2 Mions | Ville: Mions | Prix: 719000 | Surface: None | Type: Maison | Etage: None | Pièces: 5 | DPE: B
Titre: Vente Appartement 152 m2 Lyon-6e | Ville: Lyon-6e | Prix: 645000 | Surface: 152 | Type: Appartement | Etage: 1 | Pièces: 5 | DPE: E
Titre: Vente Appartement 80 m2 Rillieux-La-Pape | Ville: Rillieux-La-Pape | Prix: 299000 | Surface: None | Type: Appartement | Etage: None | Pièces: 4 | DPE: C
Titre: Vente Maison 107 m2 Theize | Ville: Theize | Prix: 370000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 4 | DPE: A
Titre: Vente Appartement 24 m2 Lyon-8e | Ville: Lyon-8e | Prix: 89000 | Surface: 24 | Type: Appartement | Etage: 5 | Pièces: 1 | DPE: C
Titre: Vente Appartement 84 m2 Lyon-8e | Ville: Lyon-8e | Prix: 320000 | Surface: 84 | Type: Appartement | Etage: 0 | Pièces: 4 | DPE: C
Titre: Vente Appartement 73 m2 Villeurbanne | Ville: Villeurbanne | Prix: 249000 | Surface: 73 | Type: Appartement | Etage: 3 | Pièces: 3 | DPE: C
Titre: Vente Appartement 152 m2 Lyon-6e | Ville: Lyon-6e | Prix: 645000 | Surface: 152 | Type: Appartement | Etage: None | Pièces: 5 | DPE: E
Titre: Vente Maison 147 m2 Saint-Genis-Les-Ollieres | Ville: Saint-Genis-Les-Ollieres | Prix: 475000 | Surface: None | Type: Maison | Etage: 4 | Pièces: 6 | DPE: C
Titre: Vente Appartement 119 m2 Lyon-6e | Ville: Lyon-6e | Prix: 555000 | Surface: 119 | Type: Appartement | Etage: 3 | Pièces: 5 | DPE: C
Titre: Vente Appartement 80 m2 Rillieux-La-Pape | Ville: Rillieux-La-Pape | Prix: 351000 | Surface: 80 | Type: Appartement | Etage: None | Pièces: 4 | DPE: C
Titre: Vente Appartement 23 m2 Lyon-2e | Ville: Lyon-2e | Prix: 141474 | Surface: 23 | Type: Appartement | Etage: 5 | Pièces: 1 | DPE: D
Titre: Vente Appartement 60 m2 Lyon-4e | Ville: Lyon-4e | Prix: 227000 | Surface: 60 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: D
Titre: Vente Appartement 121 m2 Villeurbanne | Ville: Villeurbanne | Prix: 430000 | Surface: 121 | Type: Appartement | Etage: None | Pièces: 5 | DPE: None
Titre: Vente Appartement 61 m2 Caluire-Et-Cuire | Ville: Caluire-Et-Cuire | Prix: 305000 | Surface: 61 | Type: Appartement | Etage: 2 | Pièces: 3 | DPE: D
Titre: Vente Appartement 18 m2 Lyon-5e | Ville: Lyon-5e | Prix: 144000 | Surface: 18 | Type: Appartement | Etage: None | Pièces: 1 | DPE: E
Titre: Vente Maison 254 m2 Collonges-Au-Mont-D'or | Ville: Collonges-Au-Mont-D'or | Prix: 632000 | Surface: None | Type: Maison | Etage: None | Pièces: 6 | DPE: G
Titre: Vente Appartement 118 m2 Lyon-6e | Ville: Lyon-6e | Prix: 940000 | Surface: 118 | Type: Appartement | Etage: None | Pièces: 4 | DPE: D
Titre: Vente Maison 97 m2 Condrieu | Ville: Condrieu | Prix: 165000 | Surface: 97 | Type: Maison | Etage: 0 | Pièces: 7 | DPE: E
Titre: Vente Appartement 85 m2 Lyon-7e | Ville: Lyon-7e | Prix: 425000 | Surface: 85 | Type: Appartement | Etage: 5 | Pièces: 4 | DPE: C
Titre: Vente Appartement 49 m2 Villeurbanne | Ville: Villeurbanne | Prix: 225000 | Surface: 49 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: E
Titre: Vente Appartement 116 m2 Caluire-Et-Cuire | Ville: Caluire-Et-Cuire | Prix: 201313 | Surface: 116 | Type: Appartement | Etage: 3 | Pièces: 5 | DPE: C
Titre: Vente Appartement 22 m2 Lyon-2e | Ville: Lyon-2e | Prix: 141644 | Surface: 22 | Type: Appartement | Etage: 5 | Pièces: 1 | DPE: D
Titre: Vente Appartement 91 m2 Lyon-4e | Ville: Lyon-4e | Prix: 375000 | Surface: 91 | Type: Appartement | Etage: None | Pièces: 4 | DPE: D
Titre: Vente Appartement 87 m2 Lyon-3e | Ville: Lyon-3e | Prix: 365000 | Surface: 87 | Type: Appartement | Etage: 3 | Pièces: 4 | DPE: C
Titre: Vente Maison 256 m2 Albigny-Sur-Saone | Ville: Albigny-Sur-Saone | Prix: 930000 | Surface: None | Type: Maison | Etage: None | Pièces: 6 | DPE: B
Titre: Vente Appartement 64 m2 Lyon-8e | Ville: Lyon-8e | Prix: 200000 | Surface: 64 | Type: Appartement | Etage: 4 | Pièces: 3 | DPE: C
Titre: Vente Appartement 84 m2 Rillieux-La-Pape | Ville: Rillieux-La-Pape | Prix: 359000 | Surface: 84 | Type: Appartement | Etage: None | Pièces: 4 | DPE: C
Titre: Vente Maison 73 m2 Amplepuis | Ville: Amplepuis | Prix: 149000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 3 | DPE: D
Titre: Vente Maison 128 m2 Charnay | Ville: Charnay | Prix: 315000 | Surface: 128 | Type: Maison | Etage: None | Pièces: 5 | DPE: C
Titre: Vente Appartement 53 m2 Oullins | Ville: Oullins | Prix: 179000 | Surface: 53 | Type: Appartement | Etage: None | Pièces: 3 | DPE: D
Titre: Vente Appartement 61 m2 Fontaines-Sur-Saone | Ville: Fontaines-Sur-Saone | Prix: 170000 | Surface: 61 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: D
Titre: Vente Maison 90 m2 Chaponnay | Ville: Chaponnay | Prix: 450000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 4 | DPE: D
Titre: Vente Appartement 72 m2 Lyon-1e | Ville: Lyon-1e | Prix: 374000 | Surface: 72 | Type: Appartement | Etage: None | Pièces: 3 | DPE: E
Titre: Vente Maison 195 m2 Rivolet | Ville: Rivolet | Prix: 675000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 7 | DPE: A
Titre: Vente Appartement 42 m2 Lyon-5e | Ville: Lyon-5e | Prix: 290000 | Surface: 42 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: F
Titre: Vente Appartement 64 m2 Lyon-5e | Ville: Lyon-5e | Prix: 189000 | Surface: 64 | Type: Appartement | Etage: 4 | Pièces: 4 | DPE: E
Titre: Vente Maison 242 m2 Grezieu-La-Varenne | Ville: Grezieu-La-Varenne | Prix: 770000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 10 | DPE: D
Titre: Vente Appartement 79 m2 Poleymieux-Au-Mont-D'or | Ville: Poleymieux-Au-Mont-D'or | Prix: 320000 | Surface: 79 | Type: Appartement | Etage: None | Pièces: 3 | DPE: None
Titre: Vente Appartement 89 m2 Caluire-Et-Cuire | Ville: Caluire-Et-Cuire | Prix: 490000 | Surface: 89 | Type: Appartement | Etage: None | Pièces: 4 | DPE: C
Titre: Vente Maison 390 m2 Pommiers | Ville: Pommiers | Prix: 1490000 | Surface: None | Type: Maison | Etage: None | Pièces: 7 | DPE: D
Titre: Vente Maison 185 m2 Vernaison | Ville: Vernaison | Prix: 545000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 5 | DPE: C
Titre: Vente Maison 180 m2 Villeurbanne | Ville: Villeurbanne | Prix: 1150000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 7 | DPE: C
Titre: Vente Maison 156 m2 Bron | Ville: Bron | Prix: 599000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 6 | DPE: C
Titre: Vente Appartement 61 m2 Rillieux-La-Pape | Ville: Rillieux-La-Pape | Prix: 264000 | Surface: 61 | Type: Appartement | Etage: None | Pièces: 3 | DPE: C
Titre: Vente Maison 85 m2 Serezin-Du-Rhone | Ville: Serezin-Du-Rhone | Prix: 306000 | Surface: None | Type: Maison | Etage: None | Pièces: 4 | DPE: F
Titre: Vente Appartement 65 m2 Villefranche-Sur-Saone | Ville: Villefranche-Sur-Saone | Prix: 166500 | Surface: 65 | Type: Appartement | Etage: 4 | Pièces: 3 | DPE: C
Titre: Vente Appartement 76 m2 Lyon-5e | Ville: Lyon-5e | Prix: 299000 | Surface: 76 | Type: Appartement | Etage: 4 | Pièces: 2 | DPE: E
Titre: Vente Appartement 68 m2 Caluire-Et-Cuire | Ville: Caluire-Et-Cuire | Prix: 325000 | Surface: 68 | Type: Appartement | Etage: None | Pièces: 3 | DPE: D
Titre: Vente Appartement 16 m2 Rillieux-La-Pape | Ville: Rillieux-La-Pape | Prix: 67500 | Surface: 16 | Type: Appartement | Etage: 1 | Pièces: 1 | DPE: C
Titre: Vente Appartement 47 m2 Lyon-8e | Ville: Lyon-8e | Prix: 189000 | Surface: 47 | Type: Appartement | Etage: 4 | Pièces: 2 | DPE: D
Titre: Vente Appartement 56 m2 Villefranche-Sur-Saone | Ville: Villefranche-Sur-Saone | Prix: 105000 | Surface: 56 | Type: Appartement | Etage: None | Pièces: 3 | DPE: None
Titre: Vente Appartement 51 m2 Lyon-4e | Ville: Lyon-4e | Prix: 220000 | Surface: 51 | Type: Appartement | Etage: 2 | Pièces: 2 | DPE: F
Titre: Vente Appartement 91 m2 Lyon-4e | Ville: Lyon-4e | Prix: 375000 | Surface: 91 | Type: Appartement | Etage: 3 | Pièces: 3 | DPE: D
Titre: Vente Appartement 46 m2 Lyon-4e | Ville: Lyon-4e | Prix: 199000 | Surface: 46 | Type: Appartement | Etage: 2 | Pièces: 2 | DPE: D
Titre: Vente Maison 200 m2 Pollionnay | Ville: Pollionnay | Prix: 549000 | Surface: None | Type: Maison | Etage: None | Pièces: 7 | DPE: F
Titre: Vente Appartement 45 m2 Lyon-4e | Ville: Lyon-4e | Prix: 199000 | Surface: 45 | Type: Appartement | Etage: 4 | Pièces: 2 | DPE: G
Titre: Vente Appartement 68 m2 Rillieux-La-Pape | Ville: Rillieux-La-Pape | Prix: 235000 | Surface: None | Type: Appartement | Etage: 0 | Pièces: 3 | DPE: C
Titre: Vente Appartement 64 m2 Lyon-8e | Ville: Lyon-8e | Prix: 240000 | Surface: 64 | Type: Appartement | Etage: None | Pièces: 3 | DPE: C
Titre: Vente Appartement 69 m2 Lyon-4e | Ville: Lyon-4e | Prix: 440000 | Surface: 69 | Type: Appartement | Etage: 4 | Pièces: 3 | DPE: D
Titre: Vente Maison 330 m2 Saint-Cyr-Au-Mont-D'or | Ville: Saint-Cyr-Au-Mont-D'or | Prix: 1490000 | Surface: None | Type: Maison | Etage: None | Pièces: 8 | DPE: C
Titre: Vente Appartement 66 m2 Serezin-Du-Rhone | Ville: Serezin-Du-Rhone | Prix: 273000 | Surface: 66 | Type: Appartement | Etage: 2 | Pièces: 3 | DPE: C
Titre: Vente Appartement 65 m2 Lyon-5e | Ville: Lyon-5e | Prix: 315000 | Surface: 65 | Type: Appartement | Etage: None | Pièces: 3 | DPE: C
Titre: Vente Maison 70 m2 Vaulx-En-Velin | Ville: Vaulx-En-Velin | Prix: 268000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 3 | DPE: D
Titre: Vente Appartement 70 m2 Saint-Genis-Les-Ollieres | Ville: Saint-Genis-Les-Ollieres | Prix: 247000 | Surface: 70 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: C
Titre: Vente Appartement 70 m2 Morance | Ville: Morance | Prix: 249000 | Surface: 70 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: C
Titre: Vente Appartement 31 m2 Tarare | Ville: Tarare | Prix: 56500 | Surface: 31 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: E
Titre: Vente Appartement 59 m2 Lyon-7e | Ville: Lyon-7e | Prix: 235000 | Surface: 59 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: D
Titre: Vente Maison 147 m2 Sainte-Foy-Les-Lyon | Ville: Sainte-Foy-Les-Lyon | Prix: 659000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 6 | DPE: A
Titre: Vente Appartement 41 m2 Lyon-4e | Ville: Lyon-4e | Prix: 245000 | Surface: 41 | Type: Appartement | Etage: 4 | Pièces: 2 | DPE: C
Titre: Vente Appartement 25 m2 Neuville-Sur-Saone | Ville: Neuville-Sur-Saone | Prix: 120000 | Surface: 25 | Type: Appartement | Etage: 1 | Pièces: 1 | DPE: C
Titre: Vente Maison 94 m2 La Tour-De-Salvagny | Ville: La Tour-De-Salvagny | Prix: 560000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 4 | DPE: A
Titre: Vente Appartement 89 m2 Sainte-Foy-Les-Lyon | Ville: Sainte-Foy-Les-Lyon | Prix: 275000 | Surface: 89 | Type: Appartement | Etage: None | Pièces: 4 | DPE: C
Titre: Vente Appartement 180 m2 Saint-Didier-Au-Mont-D'or | Ville: Saint-Didier-Au-Mont-D'or | Prix: 750000 | Surface: 180 | Type: Appartement | Etage: None | Pièces: 6 | DPE: None
Titre: Vente Maison 98 m2 Tarare | Ville: Tarare | Prix: 249500 | Surface: None | Type: Maison | Etage: None | Pièces: 4 | DPE: A
Titre: Vente Appartement 78 m2 Rillieux-La-Pape | Ville: Rillieux-La-Pape | Prix: 244990 | Surface: 78 | Type: Appartement | Etage: 3 | Pièces: 4 | DPE: C
Titre: Vente Appartement 60 m2 Villefranche-Sur-Saone | Ville: Villefranche-Sur-Saone | Prix: 157000 | Surface: 60 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: D
Titre: Vente Appartement 75 m2 Villeurbanne | Ville: Villeurbanne | Prix: 255000 | Surface: 75 | Type: Appartement | Etage: None | Pièces: 3 | DPE: C
Titre: Vente Maison 305 m2 Condrieu | Ville: Condrieu | Prix: 595000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 8 | DPE: D
Titre: Vente Appartement 53 m2 Ecully | Ville: Ecully | Prix: 255000 | Surface: 53 | Type: Appartement | Etage: None | Pièces: 2 | DPE: D
Titre: Vente Appartement 73 m2 Villeurbanne | Ville: Villeurbanne | Prix: 260000 | Surface: 73 | Type: Appartement | Etage: 7 | Pièces: 3 | DPE: E
Titre: Vente Maison 188 m2 Dardilly | Ville: Dardilly | Prix: 895000 | Surface: 188 | Type: Maison | Etage: None | Pièces: 8 | DPE: D
Titre: Vente Maison 160 m2 Sainte-Consorce | Ville: Sainte-Consorce | Prix: 330000 | Surface: None | Type: Maison | Etage: None | Pièces: 4 | DPE: F
Titre: Vente Appartement 48 m2 Lyon-3e | Ville: Lyon-3e | Prix: 250000 | Surface: 48 | Type: Appartement | Etage: 6 | Pièces: 2 | DPE: C
Titre: Vente Appartement 51 m2 Lyon-2e | Ville: Lyon-2e | Prix: 365000 | Surface: 51 | Type: Appartement | Etage: 2 | Pièces: 2 | DPE: D
Titre: Vente Maison 100 m2 Vaulx-En-Velin | Ville: Vaulx-En-Velin | Prix: 349000 | Surface: None | Type: Maison | Etage: 2 | Pièces: 5 | DPE: E
Titre: Vente Appartement 71 m2 Villeurbanne | Ville: Villeurbanne | Prix: 236000 | Surface: 71 | Type: Appartement | Etage: 3 | Pièces: 3 | DPE: D
Titre: Vente Appartement 84 m2 Villeurbanne | Ville: Villeurbanne | Prix: 295000 | Surface: 84 | Type: Appartement | Etage: 2 | Pièces: 4 | DPE: D
Titre: Vente Appartement 63 m2 Dardilly | Ville: Dardilly | Prix: 299000 | Surface: 63 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: C
Titre: Vente Appartement 108 m2 Poleymieux-Au-Mont-D'or | Ville: Poleymieux-Au-Mont-D'or | Prix: 260000 | Surface: 108 | Type: Appartement | Etage: 2 | Pièces: 3 | DPE: None
Titre: Vente Maison 147 m2 Curis-Au-Mont-D'or | Ville: Curis-Au-Mont-D'or | Prix: 535600 | Surface: None | Type: Maison | Etage: 1 | Pièces: 5 | DPE: D
Titre: Vente Appartement 93 m2 Lyon-4e | Ville: Lyon-4e | Prix: 425000 | Surface: 93 | Type: Appartement | Etage: 0 | Pièces: 4 | DPE: C
Titre: Vente Appartement 73 m2 Villeurbanne | Ville: Villeurbanne | Prix: 219000 | Surface: 73 | Type: Appartement | Etage: 2 | Pièces: 3 | DPE: E
Titre: Vente Appartement 31 m2 Albigny-Sur-Saone | Ville: Albigny-Sur-Saone | Prix: 138000 | Surface: 31 | Type: Appartement | Etage: None | Pièces: 1 | DPE: E
Titre: Vente Appartement 46 m2 Lyon-1e | Ville: Lyon-1e | Prix: 229000 | Surface: 46 | Type: Appartement | Etage: 4 | Pièces: 2 | DPE: F
Titre: Vente Appartement 63 m2 Villeurbanne | Ville: Villeurbanne | Prix: 200000 | Surface: 63 | Type: Appartement | Etage: None | Pièces: 2 | DPE: E
Titre: Vente Appartement 37 m2 Villeurbanne | Ville: Villeurbanne | Prix: 192000 | Surface: 37 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: C
Titre: Vente Appartement 461 m2 Bron | Ville: Bron | Prix: 1450000 | Surface: 461 | Type: Appartement | Etage: 0 | Pièces: None | DPE: B
Titre: Vente Appartement 76 m2 Bron | Ville: Bron | Prix: 200000 | Surface: 76 | Type: Appartement | Etage: 3 | Pièces: 4 | DPE: B
Titre: Vente Appartement 88 m2 Lyon-1e | Ville: Lyon-1e | Prix: 149000 | Surface: 88 | Type: Appartement | Etage: 3 | Pièces: 5 | DPE: None
Titre: Vente Appartement 102 m2 Caluire-Et-Cuire | Ville: Caluire-Et-Cuire | Prix: 320000 | Surface: 102 | Type: Appartement | Etage: 8 | Pièces: 4 | DPE: D
Titre: Vente Appartement 96 m2 Saint-Priest | Ville: Saint-Priest | Prix: 305000 | Surface: 96 | Type: Appartement | Etage: None | Pièces: 4 | DPE: B
Titre: Vente Maison 189 m2 Craponne | Ville: Craponne | Prix: 630000 | Surface: None | Type: Maison | Etage: None | Pièces: 6 | DPE: D
Titre: Vente Appartement 56 m2 Lyon-4e | Ville: Lyon-4e | Prix: 243000 | Surface: 56 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: E
Titre: Vente Maison 202 m2 Charbonnieres-Les-Bains | Ville: Charbonnieres-Les-Bains | Prix: 1190000 | Surface: None | Type: Maison | Etage: 5 | Pièces: 6 | DPE: B
Titre: Vente Appartement 103 m2 Tassin-La-Demi-Lune | Ville: Tassin-La-Demi-Lune | Prix: 409000 | Surface: 103 | Type: Appartement | Etage: 6 | Pièces: 5 | DPE: C
Titre: Vente Appartement 87 m2 Loire-Sur-Rhone | Ville: Loire-Sur-Rhone | Prix: 279000 | Surface: 87 | Type: Appartement | Etage: None | Pièces: 4 | DPE: C
Titre: Vente Appartement 23 m2 Lyon-3e | Ville: Lyon-3e | Prix: 142000 | Surface: 23 | Type: Appartement | Etage: 3 | Pièces: 1 | DPE: C
Titre: Vente Appartement 77 m2 Venissieux | Ville: Venissieux | Prix: 189000 | Surface: 77 | Type: Appartement | Etage: None | Pièces: 4 | DPE: D
Titre: Vente Appartement 41 m2 Rillieux-La-Pape | Ville: Rillieux-La-Pape | Prix: 210000 | Surface: 41 | Type: Appartement | Etage: None | Pièces: 1 | DPE: C
Titre: Vente Appartement 47 m2 Lyon-4e | Ville: Lyon-4e | Prix: 260000 | Surface: 47 | Type: Appartement | Etage: 7 | Pièces: 2 | DPE: D
Titre: Vente Appartement 76 m2 Lyon-2e | Ville: Lyon-2e | Prix: 490000 | Surface: 76 | Type: Appartement | Etage: 7 | Pièces: 4 | DPE: None
Titre: Vente Appartement 63 m2 La Tour-De-Salvagny | Ville: La Tour-De-Salvagny | Prix: 265000 | Surface: 63 | Type: Appartement | Etage: None | Pièces: 3 | DPE: C
Titre: Vente Appartement 64 m2 La Mulatiere | Ville: La Mulatiere | Prix: 230000 | Surface: 64 | Type: Appartement | Etage: 6 | Pièces: 3 | DPE: D
Titre: Vente Appartement 118 m2 Lyon-2e | Ville: Lyon-2e | Prix: 640000 | Surface: 118 | Type: Appartement | Etage: 3 | Pièces: 4 | DPE: D
Titre: Vente Appartement 38 m2 Decines-Charpieu | Ville: Decines-Charpieu | Prix: 170000 | Surface: 38 | Type: Appartement | Etage: 2 | Pièces: 2 | DPE: C
Titre: Vente Maison 115 m2 Saint-Cyr-Sur-Le-Rhone | Ville: Saint-Cyr-Sur-Le-Rhone | Prix: 437000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 5 | DPE: D
Titre: Vente Appartement 80 m2 Vaulx-En-Velin | Ville: Vaulx-En-Velin | Prix: 227000 | Surface: 80 | Type: Appartement | Etage: None | Pièces: 4 | DPE: C
Titre: Vente Appartement 104 m2 Poleymieux-Au-Mont-D'or | Ville: Poleymieux-Au-Mont-D'or | Prix: 260000 | Surface: 104 | Type: Appartement | Etage: 1 | Pièces: 4 | DPE: None
Titre: Vente Maison 126 m2 Irigny | Ville: Irigny | Prix: 395000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 5 | DPE: D
Titre: Vente Maison 166 m2 Saint-Genis-Les-Ollieres | Ville: Saint-Genis-Les-Ollieres | Prix: 688000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 6 | DPE: C
Titre: Vente Appartement 85 m2 Saint-Genis-Laval | Ville: Saint-Genis-Laval | Prix: 270000 | Surface: 85 | Type: Appartement | Etage: None | Pièces: 5 | DPE: D
Titre: Vente Maison 180 m2 Le Bois-D'oingt | Ville: Le Bois-D'oingt | Prix: 610000 | Surface: None | Type: Maison | Etage: None | Pièces: 6 | DPE: E
Titre: Vente Maison 149 m2 Cailloux-Sur-Fontaines | Ville: Cailloux-Sur-Fontaines | Prix: 695000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 5 | DPE: D
Titre: Vente Maison 127 m2 Givors | Ville: Givors | Prix: 285000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 5 | DPE: B
Titre: Vente Appartement 47 m2 Villeurbanne | Ville: Villeurbanne | Prix: 170000 | Surface: 47 | Type: Appartement | Etage: 2 | Pièces: 2 | DPE: D
Titre: Vente Appartement 82 m2 Poleymieux-Au-Mont-D'or | Ville: Poleymieux-Au-Mont-D'or | Prix: 215000 | Surface: 82 | Type: Appartement | Etage: 0 | Pièces: 3 | DPE: None
Titre: Vente Appartement 278 m2 Sathonay-Camp | Ville: Sathonay-Camp | Prix: 600000 | Surface: 278 | Type: Appartement | Etage: 1 | Pièces: 6 | DPE: D
Titre: Vente Appartement 103 m2 Condrieu | Ville: Condrieu | Prix: 190000 | Surface: None | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: C
Titre: Vente Maison 200 m2 Francheville | Ville: Francheville | Prix: 698000 | Surface: 200 | Type: Maison | Etage: None | Pièces: 9 | DPE: D
Titre: Vente Appartement 68 m2 Villeurbanne | Ville: Villeurbanne | Prix: 409000 | Surface: 68 | Type: Appartement | Etage: 11 | Pièces: 3 | DPE: None
Titre: Vente Appartement 71 m2 Lyon-7e | Ville: Lyon-7e | Prix: 375000 | Surface: 71 | Type: Appartement | Etage: 7 | Pièces: 3 | DPE: B

In [95]:
df

,titre,description,ville,type_bien,etage,prix,surface,pieces,DPE,full_description,lien
0,Vente Appartement 72 m2 Francheville,Appartement 72 m2 à Francheville,Francheville,Appartement,<NA>,269000,72.0,3,D,Decultieux Immobililer la référence depuis 196...,https://www.etreproprio.com/immobilier-2529512...
1,Vente Appartement 78 m2 Villeurbanne,Appartement 78 m2 à Villeurbanne,Villeurbanne,Appartement,3,293000,78.0,4,C,Une exclusivité DECULTIEUX Immobilier\nVILLEUR...,https://www.etreproprio.com/immobilier-2529512...
2,Vente Appartement 208 m2 Feyzin,EXCLUSIVITÉ Feyzin La Bégude Appartement r...,Feyzin,Appartement,0,380000,208.0,5,A,FEYZIN LA BÉGUDE Le confort d’une maison réc...,https://www.etreproprio.com/immobilier-2529551...
3,Vente Appartement 106 m2 Villefranche-Sur-Saone,6732- VILLEFRANCHE S/S Centre ville,Villefranche-Sur-Saone,Appartement,<NA>,239000,106.0,5,D,None,https://www.etreproprio.com/immobilier-2529521...
4,Vente Maison 154 m2 Mions,Maison d’architecte 2022 avec piscine et prest...,Mions,Maison,<NA>,719000,NaN,5,B,"Située au fond d’une impasse, dans un secteur ...",https://www.etreproprio.com/immobilier-2529560...
...,...,...,...,...,...,...,...,...,...,...,...
575,Vente Appartement 64 m2 Lyon-9e,Appartement lumineux avec magnifique vue proch...,Lyon-9e,Appartement,9,285000,64.0,3,C,L'Agence SuitHome vous propose en exclusivité ...,https://www.etreproprio.com/immobilier-2526689...
576,Vente Appartement 75 m2 Lyon-9e,"T3 de 73,6 m2 à Lyon 9 au prix de vente de 182...",Lyon-9e,Appartement,2,182300,75.0,3,C,Découvrez en exclusivité chez Lyon Métropole H...,https://www.etreproprio.com/immobilier-2526819...
577,Vente Appartement 84 m2 Tarare,Appartement 84 m2 à Tarare,Tarare,Appartement,0,120000,84.0,4,D,"A venir découvrir rapidement, à TARARE Centre ...",https://www.etreproprio.com/immobilier-2527082...
578,Vente Appartement 77 m2 Lyon-9e,"Appartement T4 de 78 m2 à Lyon 69009, Rue Féli...",Lyon-9e,Appartement,<NA>,375000,77.0,4,C,"Pour toute question ou demande d'information, ...",https://www.etreproprio.com/immobilier-2526785...
579,Vente Appartement 103 m2 Ecully,Appartement 4 pièces avec terrasse de 59m2 et ...,Ecully,Appartement,<NA>,654000,103.0,4,C,L'appartement bénéficie de grands volumes et d...,https://www.etreproprio.com/immobilier-2527547...

In [96]:
df.isna().sum()

titre                 0
description           0
ville                 0
type_bien             0
etage               197
prix                  0
surface             141
pieces                7
DPE                  58
full_description      9
lien                  0
dtype: int64

In [97]:
extracted = df["titre"].str.extract(r'(\d+(?:[.,]\d+)?)\s*m\S*')[0].str.replace(",", ".", regex=False).astype(float)
extracted

0       72.0
1       78.0
2      208.0
3      106.0
4      154.0
       ...
575     64.0
576     75.0
577     84.0
578     77.0
579    103.0
Name: 0, Length: 580, dtype: float64

In [98]:
extracted

0       72.0
1       78.0
2      208.0
3      106.0
4      154.0
       ...
575     64.0
576     75.0
577     84.0
578     77.0
579    103.0
Name: 0, Length: 580, dtype: float64

In [99]:
df["surface"] = df["surface"].fillna(extracted)

In [100]:
df.isna().sum()

titre                 0
description           0
ville                 0
type_bien             0
etage               197
prix                  0
surface               3
pieces                7
DPE                  58
full_description      9
lien                  0
dtype: int64

In [101]:
print(df.loc[df["surface"].isna(), "titre"].iloc[0])
print(df.loc[df["surface"].isna(), "description"].iloc[0])
print(df.loc[df["surface"].isna(), "full_description"].iloc[0])

Vente Appartement  Villeurbanne
Appartement   m2
IN'LI AURA vend à VILLEURBANNE (69100), un appartement T2 de 54.60 m2 au 8ème et dernier étage. Réf. 202985. Lot n°24

Dans copropriété de 72 logements construite en 1994 situé au 57/59 rue Descartes à VILLEURBANNE, proche métro République, à côté du Parc Chanteur.

Au 8eme et dernier étage avec ascenseur, agréable T2 de 54,6 m2 traversant expo EST/OUEST, clair et lumineux.

Ce bien est composé d'un séjour de 19m2 ouvrant sur une terrasse de 10m2, la cuisine de 10,7 m2 peut être ouverte sur le séjour, une chambre avec vue sur Fourvière de 12,2 m2 avec dressing attenant, une salle de bains et un WC indépendant.
Chauffage individuel gaz, double vitrage PVC.

Atouts supplémentaires :
-             Terrasse de 10m2
-             Parquet en chêne dans les pièces de vie et carrelage dans les pièces d'eau,
-             Vendu avec une place de stationnement dans parking fermé et sécurisé en sous-sol (accessible par ascenseur)

Disponible de suite. Possibilité de visite virtuelle sur demande.

Classe énergie D 187KWh/m2.an - Classe climat D 37kgCO2/m2.an. Montant estimé des dépenses annuelles d'énergie pour un usage habituel : entre 1020 € et 1450 €. Prix moyens des énergies indexés au 1er janvier 2023 (abonnements compris). Copropriété de 144 lots (dont 72 logements). Procédure en cours : Non. Charges de copropriété estimées à 940 €/an. Taxe foncière : environ 850 €

Prix de vente : 217 000 € - Honoraires à la charge du vendeur – Aucun frais d'agence.

Les informations sur les risques auxquels ce bien est exposé sont disponibles sur le site Géorisques : www.georisques.gouv.fr.

In [102]:
extracted_new = df["full_description"].str.extract(r'(\d+(?:[.,]\d+)?)\s*m\S*')[0].str.replace(",", ".", regex=False).astype(float)
extracted_new

0       32.00
1       78.75
2      208.00
3         NaN
4         NaN
        ...
575      6.00
576     73.60
577     85.00
578     78.00
579     59.66
Name: 0, Length: 580, dtype: float64

In [103]:
df["surface"] = df["surface"].fillna(extracted_new)

In [104]:
df[df["titre"]=="Vente Appartement  Sainte-Foy-Les-Lyon"]

,titre,description,ville,type_bien,etage,prix,surface,pieces,DPE,full_description,lien
348,Vente Appartement Sainte-Foy-Les-Lyon,Appartement Sainte Foy Les Lyon 2 pièce(s),Vente Appartement Sainte-Foy-Les-Lyon,Appartement,<NA>,240000,51.6,2,D,"Dans une copropriété calme et sécurisée, un ap...",https://www.etreproprio.com/immobilier-2528632...

In [105]:
df.isna().sum()

titre                 0
description           0
ville                 0
type_bien             0
etage               197
prix                  0
surface               0
pieces                7
DPE                  58
full_description      9
lien                  0
dtype: int64

In [106]:
df.to_csv("annonces_rhone.csv", index=False, encoding="utf-8-sig")

In [107]:
df["full_description"][0]

"Decultieux Immobililer la référence depuis 1962, vous propose en exclusivité à Francheville.\n\nT3 DUPLEX au dernier étage d'un immeuble récent, avec vue dégagée sur les Monts du Lyonnais.\n\nUn appartement très agréable à vivre, calme et lumineux : cuisine toute équipée, un séjour cathédrale de plus de 32m2 ouvrant sur une loggia de 12,5 m2 avec une très belle vue sur les Monts du lyonnais.\n\nL'appartement est climatisé, pour votre confort.\n\nUne suite parentale de 15 m2, avec placards intégrés et une salle de bains.\nUne chambre de 9,2 m2, une buanderie, nombreux rangements et un WC.\n\n\nChauffage individuel par pompe à chaleur pour un diagnostic énergétique performant.\nUne cave complète ce bien.\nLa copropriété est entretenue et sécurisée.\n\nProximité immédiate de tous les commerces à pieds, avec le marché le mardi.\nBus C20 et 14 pour rejoindre Lyon rapidement.\n\nLes informations sur les risques auxquels ce bien est exposé sont disponibles sur le site Géorisques : www.georisques.gouv.fr\nUn reportage photos complet sur notre site www.decultieux-immobilier.com - visite virtuelle sur demande\nA votre service pour connaître la valeur de votre bien,\nDecultieux immobilier, la référence pour votre projet immobilier sur la métropole Lyonnaise depuis 1962 - Adhérent FNAIM - Membre Property Partner International - tél [Coordonnées masquées] - Patrick MONFRAY Tél [Coordonnées masquées]\n\nHonoraires à la charge du vendeur.  Dans une copropriété de 46 lots. Aucune procédure n'est en cours. Classe énergie D, Classe climat A Montant moyen estimé des dépenses annuelles d'énergie pour un usage standard, établi à partir des prix de l'énergie de l'année 2021 : entre 880.00 et 1230.00 \x80. Les informations sur les risques auxquels ce bien est exposé sont disponibles sur le site Géorisques : georisques.gouv.fr. Ce bien vous est proposé par un agent commercial (Entreprise individuelle). \n\nVotre conseiller DECULTIEUX IMMOBILIER : Patrick MONFRAY\nAgent commercial (Entreprise individuelle)  \n  RSAC 832150510  \n  RCP 24[Coordonnées masquées].\nDecultieux immobilier, la référence pour votre projet immobilier sur la métropole Lyonnaise depuis 1962 - Adhérent FNAIM  - Membre actif du réseau international PROPERTY PARTNER - tél : [Coordonnées masquées]"

In [108]:
df

,titre,description,ville,type_bien,etage,prix,surface,pieces,DPE,full_description,lien
0,Vente Appartement 72 m2 Francheville,Appartement 72 m2 à Francheville,Francheville,Appartement,<NA>,269000,72.0,3,D,Decultieux Immobililer la référence depuis 196...,https://www.etreproprio.com/immobilier-2529512...
1,Vente Appartement 78 m2 Villeurbanne,Appartement 78 m2 à Villeurbanne,Villeurbanne,Appartement,3,293000,78.0,4,C,Une exclusivité DECULTIEUX Immobilier\nVILLEUR...,https://www.etreproprio.com/immobilier-2529512...
2,Vente Appartement 208 m2 Feyzin,EXCLUSIVITÉ Feyzin La Bégude Appartement r...,Feyzin,Appartement,0,380000,208.0,5,A,FEYZIN LA BÉGUDE Le confort d’une maison réc...,https://www.etreproprio.com/immobilier-2529551...
3,Vente Appartement 106 m2 Villefranche-Sur-Saone,6732- VILLEFRANCHE S/S Centre ville,Villefranche-Sur-Saone,Appartement,<NA>,239000,106.0,5,D,None,https://www.etreproprio.com/immobilier-2529521...
4,Vente Maison 154 m2 Mions,Maison d’architecte 2022 avec piscine et prest...,Mions,Maison,<NA>,719000,154.0,5,B,"Située au fond d’une impasse, dans un secteur ...",https://www.etreproprio.com/immobilier-2529560...
...,...,...,...,...,...,...,...,...,...,...,...
575,Vente Appartement 64 m2 Lyon-9e,Appartement lumineux avec magnifique vue proch...,Lyon-9e,Appartement,9,285000,64.0,3,C,L'Agence SuitHome vous propose en exclusivité ...,https://www.etreproprio.com/immobilier-2526689...
576,Vente Appartement 75 m2 Lyon-9e,"T3 de 73,6 m2 à Lyon 9 au prix de vente de 182...",Lyon-9e,Appartement,2,182300,75.0,3,C,Découvrez en exclusivité chez Lyon Métropole H...,https://www.etreproprio.com/immobilier-2526819...
577,Vente Appartement 84 m2 Tarare,Appartement 84 m2 à Tarare,Tarare,Appartement,0,120000,84.0,4,D,"A venir découvrir rapidement, à TARARE Centre ...",https://www.etreproprio.com/immobilier-2527082...
578,Vente Appartement 77 m2 Lyon-9e,"Appartement T4 de 78 m2 à Lyon 69009, Rue Féli...",Lyon-9e,Appartement,<NA>,375000,77.0,4,C,"Pour toute question ou demande d'information, ...",https://www.etreproprio.com/immobilier-2526785...
579,Vente Appartement 103 m2 Ecully,Appartement 4 pièces avec terrasse de 59m2 et ...,Ecully,Appartement,<NA>,654000,103.0,4,C,L'appartement bénéficie de grands volumes et d...,https://www.etreproprio.com/immobilier-2527547...

In [111]:
# Filtre les lignes où etage est NaN
df_na = df[df["etage"].isna()]

# Extrait le contexte autour de "étage" dans ces lignes
for desc in df_na["full_description"]:
    if desc:
        matches = re.findall(r'.{0,20}[eéE]tage.{0,20}', str(desc), re.IGNORECASE)
        for m in matches:
            print(repr(m))

"3 DUPLEX au dernier étage d'un immeuble récen"
'tent ce niveau. À l’étage, vous découvrirez u'
'avec lave-mains.À l’étage, place au confort :'
' duplex en dernière étage avec vue 180° sur l'
'paces enfants ou un étage privatisé : tout es'
"TRIANGLE D'OR - En étage élevé d'une résiden"
'Étage : 3ème sur 5 avec a'
'Étage : trois chambres, d'
"loisir de 40 m2 à l'étage, ainsi qu'un espace"
'Étage :'
"te sur le jardinA l'étage, une mezzanine surp"
"partement situé à l'étage 1 d'un immeuble typ"
"lle de bains et à l'étage 4 chambres. 3 autre"
"À l'étage, un magnifique esca"
'vec WC complète cet étage.'
"ne pour accéder à l'étage. 4 chambres planche"
'clusivité - Dernier étage lumineux à Tassin-l'
'm2 situé au dernier étage -- un véritable ato'
'umineux, au dernier étage, idéal pour un coup'
'6,55 m2, en dernier étage avec ascenseur, sta'
"de 90 m2 au dernier étage, bénéficiant d'atou"
'ut situé au dernier étage avec son immense ve'
'À l’étage :\r'
'm2 Carrez, niché en étage élevé, offrant une '
"A l'étage 3 chambres , une sa"
'm2 Carrez, niché en étage élevé, offrant une '
"rement équipée. À l'étage, l'espace nuit offr"
"d et 5 chambres à l'étage, 1 garage, 1 cave e"
'sant et lumineux en étage élevé, bénéficiant '
"À l'étage, la partie nuit se "
'3 – 62 m2 – Dernier étage- Ascenseur – Traver'
"nt situé au dernier étage d'un bel immeuble d"
"alle d'eau, wc. A l'étage, une vaste pièce de"
'ement T2 en dernier étage, situé au cœur du t'
"ec WC intégrés. À l'étage, une chambre complè"
"A l'étage, vous disposez de 2"
'api + : Wc à chaque étage. La maison est mito'
'Étage élevé'
"nt rénové, situé en étage élevé au sein d'une"
"Trois chambres à l'étage, dont une bénéficia"
"A L'ÉTAGE"
'3 de 91m2 : DERNIER ETAGE AVEC TERRASSE PLEIN'
' de transformation (étage + sous-sol).'
'07 - LYON - DERNIER ETAGE - T4 de 86 m2 - PIE'
'En étage élevé avec ascenseu'
"é à l'avant-dernier étage d'un immeuble de st"
' ses volumes et son étage élevé. À découvrir '
"nant 3 chambres à l'étage et une salle de bai"
"ied, 3 chambres à l'étage, et une 5ème chambr"
"t à ce niveau.  A l'étage, l'espace nuit se c"
'ant, complètent cet étage.  Côté extérieur, v'
"on vous propose à l'étage un salon séjour lum"
' propose au dernier étage un espace de 23 m2 '