In [1]:
import requests
import cloudscraper
from bs4 import BeautifulSoup
import pandas as pd
import re

donnees = []
scraper = cloudscraper.create_scraper()

for j in range(1,30):
    if j==1:  
        page = requests.get("https://www.etreproprio.com/annonces/thf.ld69#list")
    else:
        page = requests.get("https://www.etreproprio.com/annonces/thf.ld69.odd.g"+str(j)+"#list")
        
    soup = BeautifulSoup(page.content, "html.parser")
    temp = soup.find("div", class_='ep-search-list-wrapper').find_all("a")
    
    liens = []
    for i in range(len(temp)):
        if "https://www.etreproprio.com/immobilier-" in temp[i]['href']:
            liens.append(temp[i]['href'])
    
    for lien in liens:
        try:
            page_annonce = scraper.get(lien)
            soup_ = BeautifulSoup(page_annonce.content, 'lxml')

            try:
                # "Vente Appartement 75 m² Paris-14e"
                titre = soup_.find("title").text.strip()
            except:
                titre = None

            try:
                # "Appartement 75 m² à Paris-14e"
                description_h1 = soup_.find("h1", class_='annonce-immobilier').text.strip()
            except:
                description_h1 = None

            try:
                # Extrait la ville depuis le titre : "Vente Appartement 75 m² Paris-14e" → "Paris-14e"
                ville = soup_.find("title").text.strip().split("²")[-1].strip()
            except:
                ville = None

            try:
                prix = soup_.find("div", class_='ep-price').text.strip()
                prix = int(prix.replace(" ", "").replace("\xa0", "").replace("€", ""))
            except:
                prix = None

            try:
                surface = soup_.find("div", class_='ep-area').text.strip()
                surface = int(surface.replace("\xa0", "").replace("m²", "").strip())
            except:
                surface = None

            try:
                type_bien = titre.split(" ")[1]  # le 2ème mot après "Vente"
            except:
                type_bien = None

            try:
                desc_texte = soup_.find("div", class_='ep-desc-truncated').text.strip()
            except:
                desc_texte = None
            
            try:
                etage = None
                if desc_texte:
                # Cas 1 — chiffres
                    etage_match = re.search(r'(\d+)\s*(?:[eèéê][mr]?e?|°)?\s*[ée]tage', desc_texte, re.IGNORECASE)
                    if etage_match:
                        etage = int(etage_match.group(1))
                # Cas 2 — lettres
                    else:
                        etages_lettres = {
                            "premier": 1, "première": 1,
                            "deuxième": 2, "deuxieme": 2,
                            "troisième": 3, "troisieme": 3,
                            "quatrième": 4, "quatrieme": 4,
                            "cinquième": 5, "cinquieme": 5,
                            "sixième": 6, "sixieme": 6,
                            "septième": 7, "septieme": 7,
                            "huitième": 8, "huitieme": 8,
                            "neuvième": 9, "neuvieme": 9,
                            "dixième": 10, "dixieme": 10,
                        }
                        for mot, num in etages_lettres.items():
                            if mot in desc_texte.lower():
                                etage = num
                                break
                # Cas 3 — rez-de-chaussée
                    if etage is None:
                        rdc_patterns = ["rez-de-chaussée", "rez de chaussée","rez-de-chaussee", "rdc", "r.d.c"]
                        if any(p in desc_texte.lower() for p in rdc_patterns):
                            etage = 0
            except:
                etage = None

            try:
                dpe = soup_.find("div", class_='dpe-diagram').find("div", class_='selected').text.strip()
            except:
                dpe = None

            try:
                pieces = soup_.find("div", class_='ep-room').text.strip()
                pieces = int(pieces.replace("pièces", "").replace("pièce", "").strip())
            except:
                pieces = None

            print(f"Titre: {titre} | Ville: {ville} | Prix: {prix} | Surface: {surface} | Type: {type_bien} | Etage: {etage} | Pièces: {pieces} | DPE: {dpe}")

            donnees.append({
                "titre": titre,
                "description": description_h1,
                "ville": ville,
                "type_bien": type_bien,
                "etage": etage,
                "prix": prix,
                "surface": surface,
                "pieces": pieces,
                "DPE": dpe,
                "full_description": desc_texte,
                "lien": lien
            })

        except Exception as e:
            print(f"Erreur sur {lien} : {e}")
            continue

# Création du DataFrame
df = pd.DataFrame(donnees)
df["prix"] = pd.to_numeric(df["prix"], errors="coerce")
df["surface"] = pd.to_numeric(df["surface"], errors="coerce")
df["pieces"] = pd.to_numeric(df["pieces"], errors="coerce").astype("Int64")
df["etage"] = pd.to_numeric(df["etage"], errors="coerce").astype("Int64")

print(df)

Titre: Vente Maison 147 m² Saint-Genis-Les-Ollieres | Ville: Saint-Genis-Les-Ollieres | Prix: 475000 | Surface: None | Type: Maison | Etage: 4 | Pièces: 6 | DPE: C
Titre: Vente Appartement 119 m² Lyon-6e | Ville: Lyon-6e | Prix: 555000 | Surface: 119 | Type: Appartement | Etage: 3 | Pièces: 5 | DPE: C
Titre: Vente Appartement 23 m² Lyon-2e | Ville: Lyon-2e | Prix: 141474 | Surface: 23 | Type: Appartement | Etage: 5 | Pièces: 1 | DPE: D
Titre: Vente Appartement 60 m² Lyon-4e | Ville: Lyon-4e | Prix: 227000 | Surface: 60 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: D
Titre: Vente Appartement 121 m² Villeurbanne | Ville: Villeurbanne | Prix: 430000 | Surface: 121 | Type: Appartement | Etage: None | Pièces: 5 | DPE: None
Titre: Vente Appartement 61 m² Caluire-Et-Cuire | Ville: Caluire-Et-Cuire | Prix: 305000 | Surface: 61 | Type: Appartement | Etage: 0 | Pièces: 3 | DPE: D
Titre: Vente Appartement 18 m² Lyon-5e | Ville: Lyon-5e | Prix: 144000 | Surface: 18 | Type: Appartement | Etage: None | Pièces: 1 | DPE: E
Titre: Vente Appartement 118 m² Lyon-6e | Ville: Lyon-6e | Prix: 940000 | Surface: 118 | Type: Appartement | Etage: None | Pièces: 4 | DPE: D
Titre: Vente Maison 97 m² Condrieu | Ville: Condrieu | Prix: 165000 | Surface: 97 | Type: Maison | Etage: 0 | Pièces: 7 | DPE: E
Titre: Vente Appartement 85 m² Lyon-7e | Ville: Lyon-7e | Prix: 425000 | Surface: 85 | Type: Appartement | Etage: 5 | Pièces: 4 | DPE: C
Titre: Vente Appartement 49 m² Villeurbanne | Ville: Villeurbanne | Prix: 225000 | Surface: 49 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: E
Titre: Vente Appartement 22 m² Lyon-2e | Ville: Lyon-2e | Prix: 141644 | Surface: 22 | Type: Appartement | Etage: 5 | Pièces: 1 | DPE: D
Titre: Vente Appartement 91 m² Lyon-4e | Ville: Lyon-4e | Prix: 375000 | Surface: 91 | Type: Appartement | Etage: None | Pièces: 4 | DPE: D
Titre: Vente Maison 256 m² Albigny-Sur-Saone | Ville: Albigny-Sur-Saone | Prix: 930000 | Surface: None | Type: Maison | Etage: None | Pièces: 6 | DPE: B
Titre: Vente Maison 73 m² Amplepuis | Ville: Amplepuis | Prix: 149000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 3 | DPE: D
Titre: Vente Maison 128 m² Charnay | Ville: Charnay | Prix: 315000 | Surface: 128 | Type: Maison | Etage: None | Pièces: 5 | DPE: C
Titre: Vente Appartement 61 m² Fontaines-Sur-Saone | Ville: Fontaines-Sur-Saone | Prix: 170000 | Surface: 61 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: D
Titre: Vente Maison 90 m² Chaponnay | Ville: Chaponnay | Prix: 450000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 4 | DPE: D
Titre: Vente Maison 195 m² Rivolet | Ville: Rivolet | Prix: 675000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 7 | DPE: A
Titre: Vente Appartement 42 m² Lyon-5e | Ville: Lyon-5e | Prix: 290000 | Surface: 42 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: F
Titre: Vente Appartement 64 m² Lyon-5e | Ville: Lyon-5e | Prix: 189000 | Surface: 64 | Type: Appartement | Etage: 1 | Pièces: 4 | DPE: E
Titre: Vente Maison 242 m² Grezieu-La-Varenne | Ville: Grezieu-La-Varenne | Prix: 770000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 10 | DPE: D
Titre: Vente Appartement 79 m² Poleymieux-Au-Mont-D'or | Ville: Poleymieux-Au-Mont-D'or | Prix: 320000 | Surface: 79 | Type: Appartement | Etage: None | Pièces: 3 | DPE: None
Titre: Vente Appartement 89 m² Caluire-Et-Cuire | Ville: Caluire-Et-Cuire | Prix: 490000 | Surface: 89 | Type: Appartement | Etage: None | Pièces: 4 | DPE: C
Titre: Vente Maison 390 m² Pommiers | Ville: Pommiers | Prix: 1490000 | Surface: None | Type: Maison | Etage: None | Pièces: 7 | DPE: D
Titre: Vente Maison 185 m² Vernaison | Ville: Vernaison | Prix: 545000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 5 | DPE: C
Titre: Vente Maison 180 m² Villeurbanne | Ville: Villeurbanne | Prix: 1150000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 7 | DPE: C
Titre: Vente Appartement 76 m² Lyon-5e | Ville: Lyon-5e | Prix: 299000 | Surface: 76 | Type: Appartement | Etage: None | Pièces: 2 | DPE: E
Titre: Vente Appartement 16 m² Rillieux-La-Pape | Ville: Rillieux-La-Pape | Prix: 67500 | Surface: 16 | Type: Appartement | Etage: 1 | Pièces: 1 | DPE: C
Titre: Vente Appartement 47 m² Lyon-8e | Ville: Lyon-8e | Prix: 189000 | Surface: 47 | Type: Appartement | Etage: 4 | Pièces: 2 | DPE: D
Titre: Vente Appartement 56 m² Villefranche-Sur-Saone | Ville: Villefranche-Sur-Saone | Prix: 105000 | Surface: 56 | Type: Appartement | Etage: None | Pièces: 3 | DPE: None
Titre: Vente Appartement 51 m² Lyon-4e | Ville: Lyon-4e | Prix: 220000 | Surface: 51 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: F
Titre: Vente Appartement 91 m² Lyon-4e | Ville: Lyon-4e | Prix: 375000 | Surface: 91 | Type: Appartement | Etage: None | Pièces: 3 | DPE: D
Titre: Vente Appartement 46 m² Lyon-4e | Ville: Lyon-4e | Prix: 199000 | Surface: 46 | Type: Appartement | Etage: None | Pièces: 2 | DPE: D
Titre: Vente Maison 200 m² Pollionnay | Ville: Pollionnay | Prix: 549000 | Surface: None | Type: Maison | Etage: None | Pièces: 7 | DPE: F
Titre: Vente Appartement 45 m² Lyon-4e | Ville: Lyon-4e | Prix: 199000 | Surface: 45 | Type: Appartement | Etage: 4 | Pièces: 2 | DPE: G
Titre: Vente Appartement 64 m² Lyon-8e | Ville: Lyon-8e | Prix: 240000 | Surface: 64 | Type: Appartement | Etage: None | Pièces: 3 | DPE: C
Titre: Vente Appartement 69 m² Lyon-4e | Ville: Lyon-4e | Prix: 440000 | Surface: 69 | Type: Appartement | Etage: 4 | Pièces: 3 | DPE: D
Titre: Vente Maison 330 m² Saint-Cyr-Au-Mont-D'or | Ville: Saint-Cyr-Au-Mont-D'or | Prix: 1490000 | Surface: None | Type: Maison | Etage: None | Pièces: 8 | DPE: C
Titre: Vente Appartement 65 m² Lyon-5e | Ville: Lyon-5e | Prix: 315000 | Surface: 65 | Type: Appartement | Etage: None | Pièces: 3 | DPE: C
Titre: Vente Maison 70 m² Vaulx-En-Velin | Ville: Vaulx-En-Velin | Prix: 268000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 3 | DPE: D
Titre: Vente Appartement 70 m² Saint-Genis-Les-Ollieres | Ville: Saint-Genis-Les-Ollieres | Prix: 247000 | Surface: 70 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: C
Titre: Vente Appartement 70 m² Morance | Ville: Morance | Prix: 249000 | Surface: 70 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: C
Titre: Vente Appartement 31 m² Tarare | Ville: Tarare | Prix: 56500 | Surface: 31 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: E
Titre: Vente Appartement 41 m² Lyon-4e | Ville: Lyon-4e | Prix: 245000 | Surface: 41 | Type: Appartement | Etage: 4 | Pièces: 2 | DPE: C
Titre: Vente Appartement 25 m² Neuville-Sur-Saone | Ville: Neuville-Sur-Saone | Prix: 120000 | Surface: 25 | Type: Appartement | Etage: 1 | Pièces: 1 | DPE: C
Titre: Vente Maison 94 m² La Tour-De-Salvagny | Ville: La Tour-De-Salvagny | Prix: 560000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 4 | DPE: A
Titre: Vente Appartement 180 m² Saint-Didier-Au-Mont-D'or | Ville: Saint-Didier-Au-Mont-D'or | Prix: 750000 | Surface: 180 | Type: Appartement | Etage: None | Pièces: 6 | DPE: None
Titre: Vente Maison 98 m² Tarare | Ville: Tarare | Prix: 249500 | Surface: None | Type: Maison | Etage: None | Pièces: 4 | DPE: A
Titre: Vente Appartement 60 m² Villefranche-Sur-Saone | Ville: Villefranche-Sur-Saone | Prix: 157000 | Surface: 60 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: D
Titre: Vente Maison 305 m² Condrieu | Ville: Condrieu | Prix: 595000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 8 | DPE: D
Titre: Vente Appartement 53 m² Ecully | Ville: Ecully | Prix: 255000 | Surface: 53 | Type: Appartement | Etage: None | Pièces: 2 | DPE: D
Titre: Vente Appartement 73 m² Villeurbanne | Ville: Villeurbanne | Prix: 260000 | Surface: 73 | Type: Appartement | Etage: None | Pièces: 3 | DPE: E
Titre: Vente Maison 160 m² Sainte-Consorce | Ville: Sainte-Consorce | Prix: 330000 | Surface: None | Type: Maison | Etage: None | Pièces: 4 | DPE: F
Titre: Vente Appartement 51 m² Lyon-2e | Ville: Lyon-2e | Prix: 365000 | Surface: 51 | Type: Appartement | Etage: None | Pièces: 2 | DPE: D
Titre: Vente Maison 100 m² Vaulx-En-Velin | Ville: Vaulx-En-Velin | Prix: 349000 | Surface: None | Type: Maison | Etage: 2 | Pièces: 5 | DPE: E
Titre: Vente Appartement 84 m² Villeurbanne | Ville: Villeurbanne | Prix: 295000 | Surface: 84 | Type: Appartement | Etage: 2 | Pièces: 4 | DPE: D
Titre: Vente Appartement 63 m² Dardilly | Ville: Dardilly | Prix: 299000 | Surface: 63 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: C
Titre: Vente Appartement 108 m² Poleymieux-Au-Mont-D'or | Ville: Poleymieux-Au-Mont-D'or | Prix: 260000 | Surface: 108 | Type: Appartement | Etage: 2 | Pièces: 3 | DPE: None
Titre: Vente Appartement 93 m² Lyon-4e | Ville: Lyon-4e | Prix: 425000 | Surface: 93 | Type: Appartement | Etage: 0 | Pièces: 4 | DPE: C
Titre: Vente Appartement 73 m² Villeurbanne | Ville: Villeurbanne | Prix: 219000 | Surface: 73 | Type: Appartement | Etage: 2 | Pièces: 3 | DPE: E
Titre: Vente Appartement 31 m² Albigny-Sur-Saone | Ville: Albigny-Sur-Saone | Prix: 138000 | Surface: 31 | Type: Appartement | Etage: None | Pièces: 1 | DPE: E
Titre: Vente Appartement 46 m² Lyon-1e | Ville: Lyon-1e | Prix: 229000 | Surface: 46 | Type: Appartement | Etage: 4 | Pièces: 2 | DPE: F
Titre: Vente Appartement 63 m² Villeurbanne | Ville: Villeurbanne | Prix: 200000 | Surface: 63 | Type: Appartement | Etage: None | Pièces: 2 | DPE: E
Titre: Vente Appartement 37 m² Villeurbanne | Ville: Villeurbanne | Prix: 192000 | Surface: 37 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: C
Titre: Vente Appartement 76 m² Bron | Ville: Bron | Prix: 200000 | Surface: 76 | Type: Appartement | Etage: None | Pièces: 4 | DPE: B
Titre: Vente Appartement 102 m² Caluire-Et-Cuire | Ville: Caluire-Et-Cuire | Prix: 320000 | Surface: 102 | Type: Appartement | Etage: 8 | Pièces: 4 | DPE: D
Titre: Vente Appartement 96 m² Saint-Priest | Ville: Saint-Priest | Prix: 305000 | Surface: 96 | Type: Appartement | Etage: None | Pièces: 4 | DPE: B
Titre: Vente Maison 189 m² Craponne | Ville: Craponne | Prix: 630000 | Surface: None | Type: Maison | Etage: None | Pièces: 6 | DPE: D
Titre: Vente Appartement 56 m² Lyon-4e | Ville: Lyon-4e | Prix: 243000 | Surface: 56 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: E
Titre: Vente Maison 202 m² Charbonnieres-Les-Bains | Ville: Charbonnieres-Les-Bains | Prix: 1190000 | Surface: None | Type: Maison | Etage: 5 | Pièces: 6 | DPE: B
Titre: Vente Appartement 87 m² Loire-Sur-Rhone | Ville: Loire-Sur-Rhone | Prix: 279000 | Surface: 87 | Type: Appartement | Etage: None | Pièces: 4 | DPE: C
Titre: Vente Appartement 77 m² Venissieux | Ville: Venissieux | Prix: 189000 | Surface: 77 | Type: Appartement | Etage: None | Pièces: 4 | DPE: D
Titre: Vente Appartement 47 m² Lyon-4e | Ville: Lyon-4e | Prix: 260000 | Surface: 47 | Type: Appartement | Etage: 7 | Pièces: 2 | DPE: D
Titre: Vente Appartement 63 m² La Tour-De-Salvagny | Ville: La Tour-De-Salvagny | Prix: 265000 | Surface: 63 | Type: Appartement | Etage: None | Pièces: 3 | DPE: C
Titre: Vente Appartement 64 m² La Mulatiere | Ville: La Mulatiere | Prix: 230000 | Surface: 64 | Type: Appartement | Etage: 6 | Pièces: 3 | DPE: D
Titre: Vente Appartement 38 m² Decines-Charpieu | Ville: Decines-Charpieu | Prix: 170000 | Surface: 38 | Type: Appartement | Etage: 2 | Pièces: 2 | DPE: C
Titre: Vente Maison 115 m² Saint-Cyr-Sur-Le-Rhone | Ville: Saint-Cyr-Sur-Le-Rhone | Prix: 437000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 5 | DPE: D
Titre: Vente Appartement 80 m² Vaulx-En-Velin | Ville: Vaulx-En-Velin | Prix: 227000 | Surface: 80 | Type: Appartement | Etage: None | Pièces: 4 | DPE: C
Titre: Vente Appartement 104 m² Poleymieux-Au-Mont-D'or | Ville: Poleymieux-Au-Mont-D'or | Prix: 260000 | Surface: 104 | Type: Appartement | Etage: 1 | Pièces: 4 | DPE: None
Titre: Vente Maison 126 m² Irigny | Ville: Irigny | Prix: 395000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 5 | DPE: D
Titre: Vente Maison 166 m² Saint-Genis-Les-Ollieres | Ville: Saint-Genis-Les-Ollieres | Prix: 688000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 6 | DPE: C
Titre: Vente Appartement 85 m² Saint-Genis-Laval | Ville: Saint-Genis-Laval | Prix: 270000 | Surface: 85 | Type: Appartement | Etage: None | Pièces: 5 | DPE: D
Titre: Vente Maison 180 m² Le Bois-D'oingt | Ville: Le Bois-D'oingt | Prix: 610000 | Surface: None | Type: Maison | Etage: None | Pièces: 6 | DPE: E
Titre: Vente Maison 127 m² Givors | Ville: Givors | Prix: 285000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 5 | DPE: B
Titre: Vente Appartement 47 m² Villeurbanne | Ville: Villeurbanne | Prix: 170000 | Surface: 47 | Type: Appartement | Etage: 2 | Pièces: 2 | DPE: D
Titre: Vente Appartement 82 m² Poleymieux-Au-Mont-D'or | Ville: Poleymieux-Au-Mont-D'or | Prix: 215000 | Surface: 82 | Type: Appartement | Etage: 0 | Pièces: 3 | DPE: None
Titre: Vente Appartement 278 m² Sathonay-Camp | Ville: Sathonay-Camp | Prix: 600000 | Surface: 278 | Type: Appartement | Etage: 1 | Pièces: 6 | DPE: D
Titre: Vente Appartement 103 m² Condrieu | Ville: Condrieu | Prix: 190000 | Surface: None | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: C
Titre: Vente Maison 200 m² Francheville | Ville: Francheville | Prix: 698000 | Surface: 200 | Type: Maison | Etage: None | Pièces: 9 | DPE: D
Titre: Vente Maison 150 m² Fontaines-Sur-Saone | Ville: Fontaines-Sur-Saone | Prix: 629000 | Surface: None | Type: Maison | Etage: None | Pièces: 6 | DPE: D
Titre: Vente Appartement 25 m² Lyon-5e | Ville: Lyon-5e | Prix: 195000 | Surface: 25 | Type: Appartement | Etage: 1 | Pièces: 1 | DPE: F
Titre: Vente Maison 103 m² Saint-Laurent-De-Mure | Ville: Saint-Laurent-De-Mure | Prix: 448000 | Surface: None | Type: Maison | Etage: None | Pièces: 5 | DPE: C
Titre: Vente Appartement 49 m² Villeurbanne | Ville: Villeurbanne | Prix: 225000 | Surface: 49 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: E
Titre: Vente Appartement 143 m² Caluire-Et-Cuire | Ville: Caluire-Et-Cuire | Prix: 790000 | Surface: 143 | Type: Appartement | Etage: None | Pièces: 5 | DPE: C
Titre: Vente Appartement 64 m² Lyon-8e | Ville: Lyon-8e | Prix: 240000 | Surface: 64 | Type: Appartement | Etage: None | Pièces: 3 | DPE: C
Titre: Vente Appartement 67 m² Saint-Genis-Les-Ollieres | Ville: Saint-Genis-Les-Ollieres | Prix: 270000 | Surface: 67 | Type: Appartement | Etage: None | Pièces: 3 | DPE: E
Titre: Vente Appartement 77 m² Tassin-La-Demi-Lune | Ville: Tassin-La-Demi-Lune | Prix: 245000 | Surface: 77 | Type: Appartement | Etage: None | Pièces: 3 | DPE: E
Titre: Vente Appartement 50 m² Lyon-7e | Ville: Lyon-7e | Prix: 260000 | Surface: 50 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: D
Titre: Vente Maison 145 m² Corcelles-En-Beaujolais | Ville: Corcelles-En-Beaujolais | Prix: 330000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 5 | DPE: D
Titre: Vente Maison 121 m² Curis-Au-Mont-D'or | Ville: Curis-Au-Mont-D'or | Prix: 640000 | Surface: None | Type: Maison | Etage: 4 | Pièces: 6 | DPE: C
Titre: Vente Appartement 33 m² Oullins | Ville: Oullins | Prix: 149000 | Surface: 33 | Type: Appartement | Etage: None | Pièces: 2 | DPE: D
Titre: Vente Appartement 46 m² Lyon-1e | Ville: Lyon-1e | Prix: 229000 | Surface: 46 | Type: Appartement | Etage: 4 | Pièces: 2 | DPE: F
Titre: Vente Appartement 79 m² Poleymieux-Au-Mont-D'or | Ville: Poleymieux-Au-Mont-D'or | Prix: 235000 | Surface: 79 | Type: Appartement | Etage: None | Pièces: 3 | DPE: None
Titre: Vente Maison 190 m² Saint-Priest | Ville: Saint-Priest | Prix: 839000 | Surface: None | Type: Maison | Etage: None | Pièces: 9 | DPE: None
Titre: Vente Appartement 68 m² Villeurbanne | Ville: Villeurbanne | Prix: 205000 | Surface: 68 | Type: Appartement | Etage: 3 | Pièces: 3 | DPE: D
Titre: Vente Appartement 45 m² La Tour-De-Salvagny | Ville: La Tour-De-Salvagny | Prix: 289000 | Surface: None | Type: Appartement | Etage: None | Pièces: 2 | DPE: C
Titre: Vente Appartement 42 m² Meyzieu | Ville: Meyzieu | Prix: 169000 | Surface: 42 | Type: Appartement | Etage: None | Pièces: 2 | DPE: D
Titre: Vente Maison 125 m² Saint-Clement-Sur-Valsonne | Ville: Saint-Clement-Sur-Valsonne | Prix: 199900 | Surface: None | Type: Maison | Etage: 1 | Pièces: 8 | DPE: D
Titre: Vente Appartement 61 m² Lyon-1e | Ville: Lyon-1e | Prix: 225000 | Surface: 61 | Type: Appartement | Etage: None | Pièces: 2 | DPE: D
Titre: Vente Maison 130 m² Dardilly | Ville: Dardilly | Prix: 742000 | Surface: None | Type: Maison | Etage: None | Pièces: 5 | DPE: C
Titre: Vente Maison 174 m² Couzon-Au-Mont-D'or | Ville: Couzon-Au-Mont-D'or | Prix: 659000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 7 | DPE: C
Titre: Vente Maison 151 m² Communay | Ville: Communay | Prix: 305000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 7 | DPE: B
Titre: Vente Appartement 50 m² Lyon-3e | Ville: Lyon-3e | Prix: 259000 | Surface: 50 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: D
Titre: Vente Appartement 80 m² Meyzieu | Ville: Meyzieu | Prix: 369000 | Surface: 80 | Type: Appartement | Etage: 1 | Pièces: 3 | DPE: None
Titre: Vente Appartement 115 m² Lyon-4e | Ville: Lyon-4e | Prix: 445000 | Surface: 115 | Type: Appartement | Etage: None | Pièces: 4 | DPE: C
Titre: Vente Maison 157 m² Saint-Cyr-Au-Mont-D'or | Ville: Saint-Cyr-Au-Mont-D'or | Prix: 945000 | Surface: None | Type: Maison | Etage: 1 | Pièces: 6 | DPE: E
Titre: Vente Appartement 69 m² Saint-Priest | Ville: Saint-Priest | Prix: 220000 | Surface: 69 | Type: Appartement | Etage: 2 | Pièces: 3 | DPE: C
Titre: Vente Appartement 83 m² Decines-Charpieu | Ville: Decines-Charpieu | Prix: 148000 | Surface: 83 | Type: Appartement | Etage: 1 | Pièces: 4 | DPE: C
Titre: Vente Appartement 1 109 m² Lyon-7e | Ville: Lyon-7e | Prix: 5100000 | Surface: None | Type: Appartement | Etage: None | Pièces: 17 | DPE: None
Titre: Vente Appartement 83 m² Caluire-Et-Cuire | Ville: Caluire-Et-Cuire | Prix: 290000 | Surface: 83 | Type: Appartement | Etage: None | Pièces: 4 | DPE: D
Titre: Vente Appartement 62 m² Lyon-7e | Ville: Lyon-7e | Prix: 249000 | Surface: 62 | Type: Appartement | Etage: 7 | Pièces: 3 | DPE: D
Titre: Vente Maison 143 m² Craponne | Ville: Craponne | Prix: 530000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 6 | DPE: E
Titre: Vente Appartement 46 m² Lyon-1e | Ville: Lyon-1e | Prix: 229000 | Surface: 46 | Type: Appartement | Etage: 4 | Pièces: 2 | DPE: F
Titre: Vente Appartement 216 m² Villeurbanne | Ville: Villeurbanne | Prix: 900000 | Surface: 216 | Type: Appartement | Etage: None | Pièces: 7 | DPE: None
Titre: Vente Appartement 46 m² Lyon-3e | Ville: Lyon-3e | Prix: 280000 | Surface: 46 | Type: Appartement | Etage: 1 | Pièces: 2 | DPE: E
Titre: Vente Appartement 108 m² Lyon-2e | Ville: Lyon-2e | Prix: 475000 | Surface: 108 | Type: Appartement | Etage: None | Pièces: 4 | DPE: D
Titre: Vente Appartement 68 m² Villeurbanne | Ville: Villeurbanne | Prix: 299900 | Surface: 68 | Type: Appartement | Etage: None | Pièces: 3 | DPE: C
Titre: Vente Appartement 89 m² Lyon-3e | Ville: Lyon-3e | Prix: 475000 | Surface: 89 | Type: Appartement | Etage: 2 | Pièces: 4 | DPE: D
Titre: Vente Appartement 50 m² L'arbresle | Ville: L'arbresle | Prix: 125000 | Surface: 50 | Type: Appartement | Etage: None | Pièces: 2 | DPE: E
Titre: Vente Appartement 150 m² Lyon | Ville: Lyon | Prix: 419000 | Surface: 150 | Type: Appartement | Etage: 1 | Pièces: 5 | DPE: E
Titre: Vente Appartement 21 m² Bron | Ville: Bron | Prix: 105000 | Surface: 21 | Type: Appartement | Etage: None | Pièces: 1 | DPE: C
Titre: Vente Appartement 80 m² Lyon-7e | Ville: Lyon-7e | Prix: 326000 | Surface: 80 | Type: Appartement | Etage: 4 | Pièces: 3 | DPE: D
Titre: Vente Appartement 63 m² Caluire-Et-Cuire | Ville: Caluire-Et-Cuire | Prix: 229500 | Surface: 63 | Type: Appartement | Etage: None | Pièces: 3 | DPE: D
Titre: Vente Maison 145 m² Grigny | Ville: Grigny | Prix: 295000 | Surface: None | Type: Maison | Etage: 0 | Pièces: 7 | DPE: D
Titre: Vente Appartement 19 m² Lyon-7e | Ville: Lyon-7e | Prix: 85000 | Surface: 19 | Type: Appartement | Etage: 3 | Pièces: 1 | DPE: C

In [2]:
df

,titre,description,ville,type_bien,etage,prix,surface,pieces,DPE,full_description,lien
0,Vente Maison 147 m² Saint-Genis-Les-Ollieres,"Pavillon de 147m2 avec piscine, 4 chambres, gr...",Saint-Genis-Les-Ollieres,Maison,4,475000,NaN,6,C,L’agence Valdor a le plaisir de vous présenter...,https://www.etreproprio.com/immobilier-2422233...
1,Vente Appartement 119 m² Lyon-6e,Appartement 119 m² à Lyon-6e,Lyon-6e,Appartement,3,555000,119.0,5,C,"Lyon 6, Halles Paul Bocuse, appartement famili...",https://www.etreproprio.com/immobilier-2529239...
2,Vente Appartement 23 m² Lyon-2e,Investissement en residence étudiante,Lyon-2e,Appartement,5,141474,23.0,1,D,Simplicité et Tranquillité de votre investisse...,https://www.etreproprio.com/immobilier-2528410...
3,Vente Appartement 60 m² Lyon-4e,Appartement avec vue sur le Rhône ! Proche Têt...,Lyon-4e,Appartement,1,227000,60.0,3,D,LYON 4e – Cours d'Herbouville face au Parc de ...,https://www.etreproprio.com/immobilier-2528532...
4,Vente Appartement 121 m² Villeurbanne,Appartement 121 m² à Villeurbanne,Villeurbanne,Appartement,<NA>,430000,121.0,5,None,VILLEURBANNE - PLACE MARENGO\n\nAppartement du...,https://www.etreproprio.com/immobilier-2507612...
...,...,...,...,...,...,...,...,...,...,...,...
575,Vente Appartement 95 m² Lyon-5e,T4 rénové de 95 m² avec vue,Lyon-5e,Appartement,5,329000,95.0,4,E,Tassin / Limite Lyon 5. Dans résidence sécuris...,https://www.etreproprio.com/immobilier-2526522...
576,Vente Appartement 50 m² Vaulx-En-Velin,Appartement 50 m² à Vaulx-En-Velin,Vaulx-En-Velin,Appartement,<NA>,150000,50.0,2,D,Novea Immobilier a le plaisir de vous présente...,https://www.etreproprio.com/immobilier-2526010...
577,Vente Appartement 18 m² Lyon-7e,Investissement en residence étudiante,Lyon-7e,Appartement,2,102398,18.0,1,D,Un investissement patrimonial et sécurisé Inv...,https://www.etreproprio.com/immobilier-2525707...
578,Vente Appartement 32 m² Lyon-1e,Studio dernier étage avec chambre séparée - mo...,Lyon-1e,Appartement,1,224000,32.0,2,None,"Au cœur d’un secteur recherché, découvrez ce c...",https://www.etreproprio.com/immobilier-2525925...
579,Vente Maison 196 m² Mornant,Maison 196m² à mornant,Mornant,Maison,<NA>,525000,NaN,9,F,Découvrez cette belle maison parfaitement adap...,https://www.etreproprio.com/immobilier-2416957...

In [3]:
df.isna().sum()

titre                 0
description           0
ville                 0
type_bien             0
etage               252
prix                  0
surface             160
pieces                5
DPE                  55
full_description      7
lien                  0
dtype: int64

In [4]:
extracted = df["titre"].str.extract(r'(\d+(?:[.,]\d+)?)\s*m\S*')[0].str.replace(",", ".", regex=False).astype(float)
extracted

0      147.0
1      119.0
2       23.0
3       60.0
4      121.0
       ...
575     95.0
576     50.0
577     18.0
578     32.0
579    196.0
Name: 0, Length: 580, dtype: float64

In [5]:
extracted

0      147.0
1      119.0
2       23.0
3       60.0
4      121.0
       ...
575     95.0
576     50.0
577     18.0
578     32.0
579    196.0
Name: 0, Length: 580, dtype: float64

In [6]:
df["surface"] = df["surface"].fillna(extracted)

In [7]:
df.isna().sum()

titre                 0
description           0
ville                 0
type_bien             0
etage               252
prix                  0
surface               3
pieces                5
DPE                  55
full_description      7
lien                  0
dtype: int64

In [8]:
print(df.loc[df["surface"].isna(), "titre"].iloc[0])
print(df.loc[df["surface"].isna(), "description"].iloc[0])
print(df.loc[df["surface"].isna(), "full_description"].iloc[0])

Vente Appartement  Sainte-Foy-Les-Lyon
Appartement Sainte Foy Les Lyon 2 pièce(s)
Dans une copropriété calme et sécurisée, un appartement de type 2 de 51.6m² Carrez avec un jardin privatif de 40m² et une terrasse de 15m². Le bien est vendu avec une cave. Cette résidence a été construite au début des année 2000 et  se situe chemin du Vallon sur la charmante commune de Sainte Foy Les Lyon, à proximité de l'arrêt de bus de la ligne 49 (Chavril) en direction de Lyon Perrache. L'appartement est composé d'un hall d'entrée avec un dressing, un séjour pouvant être ouvert sur la cuisine équipée, une chambre avec placard murale, un Wc séparé et une salle de bains. Le Chauffage est individuel au gaz et les fenêtres sont en double vitrage PVC avec les stores roulants et manuels. Les honoraires sont à la charge du vendeur. Possibilité d'acquérir un garage fermé en sus (20 000 euros TTC) Pour une visite, Jimmy BRILLAUD au 06x10x40x32x79 Copropriété de 60 lots - dont 22 lots habitation.

In [9]:
extracted_new = df["full_description"].str.extract(r'(\d+(?:[.,]\d+)?)\s*m\S*')[0].str.replace(",", ".", regex=False).astype(float)
extracted_new

0      150.00
1      119.20
2       23.15
3       57.75
4         NaN
        ...
575     95.00
576     51.00
577     18.10
578     33.00
579    800.00
Name: 0, Length: 580, dtype: float64

In [10]:
df["surface"] = df["surface"].fillna(extracted_new)

In [11]:
df[df["titre"]=="Vente Appartement  Sainte-Foy-Les-Lyon"]

,titre,description,ville,type_bien,etage,prix,surface,pieces,DPE,full_description,lien
226,Vente Appartement Sainte-Foy-Les-Lyon,Appartement Sainte Foy Les Lyon 2 pièce(s),Vente Appartement Sainte-Foy-Les-Lyon,Appartement,<NA>,240000,51.6,2,D,"Dans une copropriété calme et sécurisée, un ap...",https://www.etreproprio.com/immobilier-2528632...

In [12]:
df.isna().sum()

titre                 0
description           0
ville                 0
type_bien             0
etage               252
prix                  0
surface               0
pieces                5
DPE                  55
full_description      7
lien                  0
dtype: int64

In [13]:
df.to_csv("annonces_rhone.csv", index=False, encoding="utf-8-sig")

In [14]:
df["full_description"][0]

'L’agence Valdor a le plaisir de vous présenter une maison de standing (construction en 2001) d’environ 150 m² habitables, idéalement située dans un quartier résidentiel recherché et particulièrement paisible de Saint-Genis-les-Ollières.\n\r\nCette maison est située au sein d’un lotissement entièrement clos et sécurisé, bénéficiant d’un système de vidéosurveillance et d’un portail électrique à l’entrée. Anciennement le bâtiment central d’un club de vacances (en effet il y avait un village vacances à Saint-Genis les Ollières il y a plus de 10 ans), il a conservé son caractère unique et ses volumes généreux. Aujourd’hui, la piscine ainsi que les espaces extérieurs attenants sont privatifs, parfaitement clos, à l’abri des regards et idéalement exposés au sud-ouest.\n\r\nDès l’entrée, vous serez immédiatement séduit par les volumes exceptionnels de la pièce de vie de plus de 60 m². Cet espace accueille une cuisine ouverte, moderne et design, baignée de lumière grâce aux larges baies vitrées offrant une vue dégagée et un accès direct au jardin.\n\r\nEn souplex, une pièce secrète et pleine de potentiel vient compléter ce bien. Elle pourra aisément accueillir une salle de cinéma (ou playstation), un espace de jeux ou encore une salle de sport, d’autant qu’un revêtement acoustique au sol est déjà installé\n\r\nL’espace nuit se compose de quatre chambres.\r\nDeux chambres d’enfants, chacune équipée de grands placards de qualité réalisés sur mesure, bénéficient d’un accès direct au jardin. La suite parentale bénéficie d’un accès direct au jardin et dispose de sa propre salle d’eau, élégamment aménagée avec double vasque et habillage en travertin au sol comme aux murs.\r\nUne quatrième chambre, également équipée d’un grand placard sur mesure, vient compléter cet espace nuit. On y retrouve également une salle de bain commune ainsi que deux toilettes et une buanderie.\n\r\nEn termes d’équipements, cette maison offre des prestations complètes et de qualité :\r\n- Volets roulants motorisés sur l’ensemble des fenêtres,\r\n- Menuiseries en bois double vitrage,\r\n- Panneaux solaires haut de gamme (EDF ENR),\r\n- Chauffage au sol et plancher rafraîchissant dans le séjour (PAC air/eau),\r\n- Adoucisseur d’eau,\r\n- Piscine au sel chauffée (PAC secondaire),\r\n- Prise individuelle pour la recharge de véhicule électrique,\r\n- Sous-sol de plus de 100 m² dédié au stockage, avec la possibilité de louer tout ou partie de l’espace grâce à un accès indépendant,\r\n- Deux places de stationnement extérieures privatives.\r\n- système son intégré au plafond (séjour, chambre parentale, salle de bain) \n\r\nContactez dès maintenant Flavien COTTANCIN au O6 89 63 42 88 pour organiser une visite. RSAC 839 127 545 - Responsabilité Civile Professionnelle n° RD01686968W. Les informations relatives aux risques naturels sont disponibles sur http://www.georisques.gouv.fr\r\nCharges mensuelles de copropriété pour un montant de 305€. Pas de procédure en cours.'

In [15]:
df

,titre,description,ville,type_bien,etage,prix,surface,pieces,DPE,full_description,lien
0,Vente Maison 147 m² Saint-Genis-Les-Ollieres,"Pavillon de 147m2 avec piscine, 4 chambres, gr...",Saint-Genis-Les-Ollieres,Maison,4,475000,147.0,6,C,L’agence Valdor a le plaisir de vous présenter...,https://www.etreproprio.com/immobilier-2422233...
1,Vente Appartement 119 m² Lyon-6e,Appartement 119 m² à Lyon-6e,Lyon-6e,Appartement,3,555000,119.0,5,C,"Lyon 6, Halles Paul Bocuse, appartement famili...",https://www.etreproprio.com/immobilier-2529239...
2,Vente Appartement 23 m² Lyon-2e,Investissement en residence étudiante,Lyon-2e,Appartement,5,141474,23.0,1,D,Simplicité et Tranquillité de votre investisse...,https://www.etreproprio.com/immobilier-2528410...
3,Vente Appartement 60 m² Lyon-4e,Appartement avec vue sur le Rhône ! Proche Têt...,Lyon-4e,Appartement,1,227000,60.0,3,D,LYON 4e – Cours d'Herbouville face au Parc de ...,https://www.etreproprio.com/immobilier-2528532...
4,Vente Appartement 121 m² Villeurbanne,Appartement 121 m² à Villeurbanne,Villeurbanne,Appartement,<NA>,430000,121.0,5,None,VILLEURBANNE - PLACE MARENGO\n\nAppartement du...,https://www.etreproprio.com/immobilier-2507612...
...,...,...,...,...,...,...,...,...,...,...,...
575,Vente Appartement 95 m² Lyon-5e,T4 rénové de 95 m² avec vue,Lyon-5e,Appartement,5,329000,95.0,4,E,Tassin / Limite Lyon 5. Dans résidence sécuris...,https://www.etreproprio.com/immobilier-2526522...
576,Vente Appartement 50 m² Vaulx-En-Velin,Appartement 50 m² à Vaulx-En-Velin,Vaulx-En-Velin,Appartement,<NA>,150000,50.0,2,D,Novea Immobilier a le plaisir de vous présente...,https://www.etreproprio.com/immobilier-2526010...
577,Vente Appartement 18 m² Lyon-7e,Investissement en residence étudiante,Lyon-7e,Appartement,2,102398,18.0,1,D,Un investissement patrimonial et sécurisé Inv...,https://www.etreproprio.com/immobilier-2525707...
578,Vente Appartement 32 m² Lyon-1e,Studio dernier étage avec chambre séparée - mo...,Lyon-1e,Appartement,1,224000,32.0,2,None,"Au cœur d’un secteur recherché, découvrez ce c...",https://www.etreproprio.com/immobilier-2525925...
579,Vente Maison 196 m² Mornant,Maison 196m² à mornant,Mornant,Maison,<NA>,525000,196.0,9,F,Découvrez cette belle maison parfaitement adap...,https://www.etreproprio.com/immobilier-2416957...